1. What is a Python library? Why ^o we use Python libraries?
=> It is a collection of codes which is already written and we can utilise those modules in our projects

2. What is the ^ifference between Numpy array an^ List?
=> List is heterogenous in nature while numpy array is homogenous in nature

3. Fin^ the shape, size an^ ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr.ndim

2

In [6]:
arr.size

12

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.shape

(3, 4)

In [9]:
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [10]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr2[0]

array([1, 2, 3, 4])

In [12]:
arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [13]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr3[2,1:3]

array([10, 11])

In [15]:
arr4 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [16]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr4[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

In [18]:
import random
arr = np.random.randint(0,2,(2,3))
arr

array([[0, 1, 1],
       [0, 0, 1]])

In [19]:
arr = np.random.rand(2,3)
arr
=> Generatees a 2,3 matrix of random values

SyntaxError: invalid syntax (326867135.py, line 3)

In [ ]:
arr1 = np.random.randn(2,3)
arr1
=>Generates a 2,3 matrix but with normal distribution

In [ ]:
arr3  = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr4 = np.expand_dims(arr3, axis =1)
arr4.shape

In [ ]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr2 = arr.T
arr2

In [ ]:
arr1 =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
arr1 * arr2

In [ ]:
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr3 = arr1 @ arr2
arr3
# can't perfom matric multiplication

In [20]:
arr1 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [22]:
arr2 -arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
arr2 / arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
#12. Which function in Numpy can be use^ to swap the byte or^er of an array?
byteswap

NameError: name 'byteswap' is not defined

In [25]:
#13. What is the significance of the np.linalg.inv function?
=>compute the inverse of a square matrix.

SyntaxError: invalid syntax (861093888.py, line 2)

#13. What is the significance of the np.linalg.inv function?
=>It reshapes the data without changing the data inside the array. Whenever we reshape we have to amke sure the elemtns remains the same

In [30]:
# arr1.reshape(2,4,3)
# arr1.shape
arr1.reshape(6,2)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
#15. What is broa^casting in Numpy?
# => carrying out an operation on all the elements of the array
arr1 + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])